## Service definition ##
application:
  schemaVersion: 1.0.0-preview1
  name: BastaDemo2018
  properties:
    services:
      - name: Platform
        properties:
          description: Platform description.
          osType: Windows
          codePackages:
            - name: Platform
              image: platform:dev
              endpoints:
                - name: PlatformListener
                  port: 20000
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20000
                - name: RestaurantServiceName
                  value: restaurantservice.bastademo2018
                - name: RestaurantServicePort
                  value: 20004
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: BastaDemo2018Network